namespace Feirapp.Domain.Services.GroceryItems.Methods.GetGroceryItemsByStore;

public record GetGroceryItemFromStoreIdResponse(GetGroceryItemsByStoreStoreDto Store, List<GetGroceryItemsByStoreGroceryItemDto> Items);