namespace Feirapp.Domain.Services.GroceryItems.Methods.GetGroceryItemsByStore;

public record GetGroceryItemsByStoreIdResponse(GetGroceryItemsByStoreStoreDto Store, List<GetGroceryItemsByStoreGroceryItemDto> Items);