// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Feirapp.Tests.Bdd.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ManageGroceryItemsFeature : object, Xunit.IClassFixture<ManageGroceryItemsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AcceptanceCriteria.feature"
#line hidden
        
        public ManageGroceryItemsFeature(ManageGroceryItemsFeature.FixtureData fixtureData, Feirapp_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Bdd/Features", "Manage Grocery Items", "Organiza Grocery Items", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Grocery Items are created successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "Manage Grocery Items")]
        [Xunit.TraitAttribute("Description", "Grocery Items are created successfully")]
        public void GroceryItemsAreCreatedSuccessfully()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Grocery Items are created successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Price",
                            "Cean",
                            "Brand",
                            "Store Name",
                            "Purchase Date",
                            "Image Url",
                            "Category"});
                table1.AddRow(new string[] {
                            "Biscoito",
                            "1234.56",
                            "7898458753257",
                            "treloso",
                            "Aib",
                            "2020-10-10",
                            "img.url.png",
                            "1"});
                table1.AddRow(new string[] {
                            "Bolacha",
                            "1234.56",
                            "7898458753257",
                            "vitarella",
                            "MIX MATEUS",
                            "2020-10-10",
                            "img.url.png",
                            "1"});
                table1.AddRow(new string[] {
                            "Detergente",
                            "1234.56",
                            "7898458753257",
                            "ype",
                            "BOM PREÇO",
                            "2020-10-10",
                            "img.url.png",
                            "1"});
                table1.AddRow(new string[] {
                            "Cheetos Lua",
                            "1234.56",
                            "7898458753257",
                            "elma chips",
                            "VERD FRUT",
                            "2020-10-10",
                            "img.url.png",
                            "1"});
#line 4
        testRunner.When("the client provides the right Grocery Item data", ((string)(null)), table1, "When ");
#line hidden
#line 10
        testRunner.Then("return the Grocery Item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ManageGroceryItemsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ManageGroceryItemsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
