services:
  feirapp-api:
    image: ${DOCKER_REGISTRY-}feirapp-api:1.1
    container_name: feirapp-api
    build:
      context: .
      dockerfile: Feirapp.API/Dockerfile
    depends_on:
      - feirapp-db
    ports:
      - "5000:8080"
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;"
        
  feirapp-db:
    image: postgres:16
    container_name: feirapp-db
    environment:
      POSTGRES_DB: feirapp-db
      POSTGRES_USER: feirapp-user
      POSTGRES_PASSWORD: feirapp-password
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
      
volumes:
  db-volume:
