services:
  feirapp-api:
    image: ${DOCKER_REGISTRY-}feirapp-api:1.1
    container_name: feirapp-api
    build:
      context: .
      dockerfile: Feirapp.API/Dockerfile
    depends_on:
      - feirapp-db
    ports:
      - "5000:8080"
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;"
        
  feirapp-db:
    image: mysql:8.3.0
    container_name: feirapp-db
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: feirapp-user
      MYSQL_PASSWORD: feirapp-password
      MYSQL_DATABASE: feirapp-db
      
volumes:
  db-volume:
